### ISSUE TITLE
what version is this?

### ISSUE THREAD

**Issue by porres** [reduzent/pd-ggee#1]
hi, is this one of the versions in deken?

marked as 0.27?

how different is it from 0-0extended?

**Comment by porres** [comment]
moreover, are you maintaining this in any way? Or just put it here to upload to deken?

**Comment by reduzent** [comment]
Since I'm using it myself, I didn't want rely on the transitional port from Pd-extended. Because no one else provided a 'canonical' release in Deken, I went ahead and made one. 

I'm not a C coder, so I probably won't be able to fix things in the C part. However, if you submit issues or feature requests, I'm willing to do my best to incorporate any fixes. If nobody else claims responsibility for this library, consider me the responsible person.

**Comment by reduzent** [comment]
I should have said: As long as nobody else claims responsibility, [...]

**Comment by porres** [comment]
> Since I'm using it myself, I didn't want rely on the transitional port from Pd-extended. Because no one else provided a 'canonical' release in Deken, I went ahead and made one.

Sorry, I don't understand what you mean by a 'canonical' release.

So, is this one marked as 0.27 in deken? And how different is it from 0-0extended (which I'm assuming it's 0.26)?

**Comment by reduzent** [comment]
i just used the version number that was included in the sources.. i didn't invent any and also i barely touched the sources besides converting the build system to pd-lib-builder.

Now, i remember my motivation behind doing my own release. The pd-extended ports are only available for a subset of platform/architectures that I wanted to be supported. In order to make it easy for myself to create new builds and to publish new Deken releases, I converted everything to pd-lib-builder. I consider the versions tagged 0.0extended to be only transitional and not easy to reproduce. I wanted to make easily reproducible builds, so that it will be easier in the future to fix bugs in that library. 

By 'canonical' I mean: Nobody declared themselves maintainers of the ggee library and nobody did put a release on Deken (besides the 0.0extended version, which was put there to make the transition from old Pd-extended to Pd-vanilla with Deken a bit easier and which is not a real release).

**Comment by porres** [comment]
I see, so basically it is the same version as v0-0, that's what I really wanted to know, thanks. I'm keeping track of which libraries are repeated in deken, and I already said in the list I find the 'v0-0-extended' name very confusing. It'd be best for this package if the 'v0-0-extended' one would be just deleted as it is a duplicate, right?

**Comment by porres** [comment]
out of curiosity, what objects do you use from here?

**Comment by reduzent** [comment]
I don't have a strong opinion on this, but I tend to think that it'd be better to keep the 0.0extended versions around, since those are the builds most similar to the ones you found in Pd-extended. Any later version might be different.

**Comment by reduzent** [comment]
It's actually pretty stupid: In netpd I need to check for the existence of some files, which could be easily done with [textfile] in my case. However, whenever a file couldn't be found, it caused an error message to the console. So, I was looking for a way to do it without triggering a message and did so by using [getdir] from ggee and [readdir] from moocow..... pretty stupid and insane, but I still considered it better than printing an error each time back then..

**Comment by reduzent** [comment]
BTW, if the ELSE library has some way to check for the existence of a pd file, I'd probably switch

**Comment by porres** [comment]
> I don't have a strong opinion on this, but I tend to think that it'd be better to keep the 0.0extended versions around, since those are the builds most similar to the ones you found in Pd-extended. 

My opinion (and very strong one) is that the version should be explicitly mentioned in the release, cause v0-0 seems just insane and opens up the gates to hell in silly discussions like this. If thew versioning was clear, I wouldn't have a doubt or issue. And this all came about cause I wanted to tell my students if the versions were different in any way and how...

If you think this is different in any way, maybe change the version name, put a changelog (like 'porting to libpdbuilder') and release under 0.28 or something. Then we can change the name of v0-0 to 0.27, that sounds better. And I'm willing to do all that eventually (rename all v0-0 libraries), even though I'll probably have to pick a fight for it on the Pd list :)

the only thing now is that I'm terribly busy with ELSE as you might realize, so I don't see me doing that anytime soon.

Anyhow, if I see any newer version (or 'other' version) than v0-0 extended, I assume it is a newer one, which in this case it kinda is, though you say you didn't create a newer version.

Well, guess where I'm getting at is that you could try and make a new 0.28 version name, even though you didn't do much. And one day, eventually, I'll see if I can rename all those v0-0-extended versions around. 

what do you say?

**Comment by porres** [comment]
> if the ELSE library has some way to check for the existence of a pd file, I'd probably switch

I could think of a way to do that ;) and you can open a request here please https://github.com/porres/pd-else/issues

**Comment by porres** [comment]
btw, have you seen this? https://github.com/pure-data/pure-data/pull/150

I guess you can try and reopen that issue in a more general sense, like dan suggested, and see if anything like that has a chance to get into vanilla. Though I could offer an external option in the meantime.

**Comment by porres** [comment]
Hi, I see this issue is still open and still unanswered.

Have you considered bumping your version to 0.28 to reflect the porting to libpdbuilder?

**Comment by reduzent** [comment]
I don't see a need in bumping the version.. I didn't add features nor did I fix bugs. I simply modified the build system. I believe this doesn't warrant a new release.

**Comment by porres** [comment]
>  I simply modified the build system. I believe this doesn't warrant a new release.

I actually agree, but this still leaves us with another issue, which is the fact that there are two equal versions up in deken. Having a duplicate version is confusing, and I guess the way to fix this is by removing the v0-0extended. And then this doesn't really concern this repository, right? But then, your personal opinion was that it should stay there, right? Well, maybe I should take this to the pd list. In any case, only IOhannes could take it down.

Moreover, I'd have a fix or another I'd like to see in ggee, as in the Pull Request you might have seen. This would call for another release...

and, finally, can you show me your patch where you use [getdir] and [readdir]? I'll see if I can think of an external for that

cheers

**Comment by reduzent** [comment]
I don't understand what you think is the problem with having v0.0extended and v0.27 in Deken. OK, both share more or less the same code, but one is there for the transition from Pd-extended. 

When I bump the version, the objects both packages contain are not less the same.

The abstraction that is using [getdir] and [readdir] is [[netpd-if-file]](https://github.com/reduzent/netpd/blob/master/includes/netpd-if-file.pd) from netpd. It expects a path as input and returns 0 or 1, depending on whether such a file exists.

**Comment by porres** [comment]
> I don't understand what you think is the problem with having v0.0extended and v0.27 in Deken. 

Because v0.0extended is actually v0.27. Thus, it is a duplicate, and it's just wrong to have a duplicate version for download. It is confusing for the end user, as we also discussed in https://github.com/reduzent/pd-ggee/pull/3#event-1362198319 

There are two solutions for this: delete v0.0extended from deken or bump the version from this repository to v0.28

> OK, both share more or less the same code, but one is there for the transition from Pd-extended.

I don't understand what you mean by "transition from Pd-extended". If they have the exact same objects and documentation, they basically the same and this one only provides a different build system.

But if you think they are different and both should be there, I think bumping it to v0.28 would be the solution. Yeah, only changing the build system might not be much of an ordeal, but **any** change in the code, be it under the hood or not, calls for a different version, so it is more than usual to make a version bump just for something like that. Specially if you want to keep v0.0extended in deken.

Now, goimg back to the recent merge of that Pull Request of https://github.com/reduzent/pd-ggee/pull/3#event-1362198319  we have yet more reasons to make this a bumped version to v0.28. I'd be willing to go through the trouble of uploading this to deken as such.

But you know, we need to keep it organized so it doesn't get more confusing than it is.

ps. I'm now at least fixing a relevant bug in [envgen] where it crashes pd if you don't have a matching [receive] object. That's an easier bug to fix than the sustain one. Doing that now.

**Comment by porres** [comment]
> The abstraction that is using [getdir] and [readdir] is [netpd-if-file] from netpd. It expects a path as input and returns 0 or 1, depending on whether such a file exists.

Well, this is already in my repo, and I'm including it as a request from you ;) - it's a much simpler version of [getdir] 

<img width="562" alt="screen shot 2017-11-30 at 01 26 11" src="https://user-images.githubusercontent.com/5360142/33411619-c767fb8a-d56d-11e7-9cb5-2a18a208aa9a.png">

**Comment by porres** [comment]
https://github.com/porres/pd-else/blob/master/classes/dir.c

**Comment by porres** [comment]
> BTW, if the ELSE library has some way to check for the existence of a pd file, I'd probably switch

Oh, you mean I should merge [getdir] and [readdir] into a single object?

**Comment by porres** [comment]
> Oh, you mean I should merge [getdir] and [readdir] into a single object?

I've incremented new features to [else/dir], now it can dump all the files from a directory (patch's by default). With this object, you don't need either [getdir] or [readdir] and your patch becomes much simpler. All you need is a "dump" message to [dir]. You could also insert the files in a [text] object and then search for it to see if you can find it, seems like a better deal.

<img width="565" alt="screen shot 2017-12-02 at 12 42 37" src="https://user-images.githubusercontent.com/5360142/33516711-6e4db402-d75e-11e7-92f4-00733ce903f6.png">

**Comment by porres** [comment]
screenshot 
<img width="568" alt="screen shot 2017-12-02 at 12 46 13" src="https://user-images.githubusercontent.com/5360142/33516729-d58bfc50-d75e-11e7-8b69-752c6612c3be.png">
